# Generated by Django 5.1.2 on 2025-10-06 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Unique identifier for the conversation session', max_length=255)),
                ('message', models.TextField(help_text='The actual message content')),
                ('message_type', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], help_text='Whether this message is from user or bot', max_length=10)),
                ('query_type', models.CharField(blank=True, choices=[('text', 'Text Query'), ('calculation', 'Calculation Query')], help_text='Type of query detected (text or calculation)', max_length=20, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this message was created')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the message', null=True)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['session_id', 'timestamp'], name='chatbot_cha_session_488328_idx'), models.Index(fields=['-timestamp'], name='chatbot_cha_timesta_c63751_idx')],
            },
        ),
    ]
